sdk: /usr/local/opt/dart/libexec
install_path: /Users/anton/crossdart-install
output_path: /Users/anton/crossdart-out
templates_path: /Users/anton/projects/mixbook/crossdart/templates
pub_cache_path: /Users/anton/.pub-cache
db_login: root
db_password:
db_host: localhost
db_port: 3306
db_name: crossdart2
