name: crossdart
version: 0.4.2
author: Anton Astashov <anton.astashov@gmail.com>
description:
  Generates crossdart.info content.
  Also, allows to generate metadata for the project, and then use
  the Chrome Extension (also included) to add links to the declarations
  on Github
homepage: https://www.crossdart.info
environment:
  sdk: ">=1.16.0 <2.0.0"
dependencies:
  pub_semver: ^1.2.4
  intl: ^0.13.0
  package_config: ^0.1.3
  args: ^0.13.4+2
  collection: ^1.8.0
  resource: ^1.1.0
  logging: ^0.11.3
  yaml: ^2.1.9
  http: ^0.11.3+7
  googleapis_auth: ^0.2.3+3
  googleapis: ^0.27.0
  analyzer: ^0.27.3

dev_dependencies:
  unittest: any
