name: crossdart
version: 0.2.1
author: Anton Astashov <anton.astashov@gmail.com>
description:
  Generates crossdart.info content.
  Also, allows to generate metadata for the project, and then use
  the Chrome Extension (also included) to add links to the declarations
  on Github
homepage: https://www.crossdart.info
environment:
  sdk: ">=1.16.0 <2.0.0"
dependencies:
  args: '>=0.12.2'
  analyzer: '>=0.25.0'
  googleapis: any
  googleapis_auth: any
  pub_semver: any
  collection: any
  intl: '>=0.8.6'
  logging: '>=0.9.3'
  http: '>=0.11.1'
  yaml: '>=2.1.2'
  package_config: any
  resource: any

dev_dependencies:
  unittest: any
