name: crossdart
version: 0.0.1
author: Anton Astashov <anton.astashov@gmail.com>
description:
  Generates crossdart.info content.
  Also, allows to generate metadata for the project, and then use
  the Chrome Extension (also included) to add links to the declarations
  on Github
homepage: http://crossdart.info
environment:
  sdk: '>=1.8.0'
dependencies:
  analyzer: '>=0.24.0'
  collection: '>=1.1.0'
  intl: '>=0.8.6'
  logging: '>=0.9.3'
  http: '>=0.11.1'
  sqljocky: '>=0.11.0'
  yaml: '>=2.1.2'

dev_dependencies:
  unittest: any
